# -*- coding: utf-8 -*-
"""Module_End_Project_Social_Media_Engagement_Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ixojsJ2FqwF6Ejnozho9oVXN8ozJpN7

# **Social Media Engagement Analytics Using Python**
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

# Ignore all warnings
warnings.filterwarnings("ignore")

#Reading Dataset
url = "https://raw.githubusercontent.com/GeethaGunasekaran1/Dataset_rep/main/social_media_engagement_5000.csv"

df = pd.read_csv(url)
df.head()

# Checking basic info
print(f"Basic informations:n")
print(f"-"*35)
print(df.info())
print(f"-"*35)

# Summary of statistics for numerical columns
print(f"Summuary statistics of Numerical columns :")
print(f"-"*35)
print(df.describe().round(2))
print(f"-"*35)

# View first 5 rows
print("Head (first 5 rows):")
print(df.head())

# View last 5 rows
print("\nTail (last 5 rows):")
print(df.tail())

# Shape of dataset (rows, columns)
print("\nShape of dataset:")
print(df.shape)

# List of column names
print("\nColumns in dataset:")
print

"""# **Duplicate Handling**
Detection: Applied df.duplicated() to check for duplicate rows.

There are no duplicate values in the dataset


"""

# Checking for missing values

print(f"Missing Values:  \n")
print(f"-"*15)
print(f"{df.isnull().sum()}")
print(f"-"*15)

#Checking for Duplicates
print(f"-"*15)
print(f"Duplicate Values:  \n")
print(f"{df.duplicated().sum()}")
print(f"-"*15)

"""# **Data Formatting & Standardization **
• Incorrect Data Types: Converted posted_at to datetime, numeric fields to
int/float.
"""

# Converting posted_at column to datetime
df['posted_at'] = pd.to_datetime(df['posted_at'], errors='coerce')

# Verifying the change
print(df['posted_at'].dtypes)
print(df['posted_at'].head())

"""# **1. Handling Missing Data **
• Detection: Used isnull() and isna() to identify missing values across columns.
1.  Treatment:
*   Numeric fields (likes, comments, shares, watch_time): Imputed using median to reduce skew impact.
*   Categorical fields (gender, sentiment, post_type): Filled using mode
or "Unknown" where mode was unavailable.
*   Date fields: Forward/backward fill applied to maintain continuity in time
series.
"""

#Handling Missing values

# filling numeric columns with median

df['age'].fillna(df['age'].median(), inplace=True)
df['likes'].fillna(df['likes'].median(), inplace=True)
df['comments'].fillna(df['comments'].median(), inplace=True)
df['shares'].fillna(df['shares'].median(), inplace=True)

# Filling categorical with mode

df['gender'].fillna(df['gender'].mode()[0], inplace=True)
df['sentiment'].fillna(df['sentiment'].mode()[0], inplace=True)

# Ensuring for non missing values after filling null values

print(f"Missing Values:  \n")
print(f"-"*15)
print(f"{df.isnull().sum()}")
print(f"-"*15)

# Numeric columns (exclude IDs)
num_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
num_cols = [col for col in num_cols if col not in ['user_id', 'post_id']]

# Categorical columns
cat_cols = df.select_dtypes(include=['object', 'bool']).columns.tolist()

print("Numeric Columns:", num_cols)
print("Categorical Columns:", cat_cols)

#Checking for unique values in categorical columns

for col in cat_cols:
  print(df[col].unique())

#Checking Unrealisticc values for likes, comments and shares

print(df[num_cols].min().astype(int))
print(df[num_cols].max().astype(int))

"""# **Feature Cleaning **

1.   Hashtag Count: Extracted from text fields using string split → df['hashtag_count'].
2.   Sentiment Labels: Cleaned inconsistent casing and spelling.
*  Engagement Rate: Verified formula consistency:
*  Engagement Rate=Likes+Comments+SharesFollowers×100


"""

# Create a new column for hashtag count
df['hashtag_count'] = df['hashtags'].apply(
    lambda x: len(str(x).split(',')) if pd.notnull(x) else 0
)

# Quick check
print(df[['hashtags','hashtag_count']].head(20))

#Analyze Categorical Distributions

# Loop through all categorical columns
for col in cat_cols:
    print(f"\n--- {col} ---")
    print(df[col].value_counts())
    print("Unique:", df[col].unique())
    print("nunique:", df[col].nunique())

#Correlation Matrix for Numeric Fields
corr_matrix = df[num_cols].corr()

plt.figure(figsize=(10,6))
sns.heatmap(corr_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Matrix of Numeric Fields")
plt.show()

# Average likes by post type
avg_likes_posttype = df.groupby('post_type')['likes'].mean().round(2)
print(f"\n---Average Likes by Posttype---")
print(avg_likes_posttype)

# Impressions by country
impressions_country = df.groupby('country')['impression_count'].mean().round(2)
print(f"\n----Impressions by Countries ---")
print(impressions_country)

# Engagement by sentiment
engagement_sentiment = df.groupby('sentiment')['engagement_rate'].mean().round(2)
print(f"\n--- Engagement by sentiment ---")
print(engagement_sentiment)

#Creating New Fields: Engagement Score (likes + comments + shares):

df['engagement_score'] = df['likes'] + df['comments'] + df['shares']

#Displaying Newly created fields by plots

sns.barplot(x='post_type', y='engagement_score', data=df, estimator='mean')
plt.title("Average Engagement Score by Post Type")
plt.show()

sns.barplot(x='country', y='impression_count', data=df, estimator='mean')
plt.xticks(rotation=45)
plt.title("Average Impressions by Country")
plt.show()

sns.barplot(x='sentiment', y='engagement_score', data=df, estimator='mean')
plt.title("Engagement Score by Sentiment")
plt.show()

cols = ['likes','comments','shares','watch_time_sec','engagement_rate','follower_count']

for col in cols:
    print(f"\n--- {col} ---")
    print("Mean:", df[col].mean())
    print("Median:", df[col].median())
    print("Mode:", df[col].mode()[0])
    print("Std Dev:", df[col].std())
    print("Variance:", df[col].var())
    print("25th Percentile:", df[col].quantile(0.25))
    print("50th Percentile:", df[col].quantile(0.50))
    print("75th Percentile:", df[col].quantile(0.75))
    print("Skewness:", df[col].skew())
    print("Kurtosis:", df[col].kurtosis())
    print("Range:", df[col].max() - df[col].min())


#Exploring the statistics of req. column

print(df[num_cols].describe().astype(int))

#checking for outliers
fig, axes = plt.subplots(nrows=4, ncols=2, figsize=(20, 15))
axes =axes.flatten()
for i, col in enumerate(num_cols):
  sns.boxplot(data=df[col],ax=axes[i])
  axes[i].set_title(f'Distribution of {col}')
plt.tight_layout()
plt.show()

df['engagement_rate'].skew()

df['engagement_rate'].kurtosis()

sns.histplot(df['engagement_rate'], kde=True)
plt.title("Before Transformation")
plt.show()

"""# **Outlier Treatment **
1.   Applied IQR method to detect extreme outliers in ‘engagement_rate’ column

2. • Outliers were capped and log transformed for separate analysis.



"""



#Handling outliers in "engagement_rate"

Q1 = df['engagement_rate'].quantile(0.25)
Q3 = df['engagement_rate'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df['engagement_rate'] < lower_bound) | (df['engagement_rate'] > upper_bound)]
print("Number of outliers:", len(outliers))

df['engagement_rate_capped'] = np.where(df['engagement_rate'] > upper_bound, upper_bound,
                                 np.where(df['engagement_rate'] < lower_bound, lower_bound, df['engagement_rate']))

df['engagement_rate_capped'].skew()

df['engagement_rate_log'] = np.log1p(df['engagement_rate_capped'])

df['engagement_rate_log'].skew()

# Displaying 'engagement_rate after reduction of skewness
sns.histplot(df['engagement_rate_log'], kde=True)
plt.title("After Transformation")
plt.show()
sns.boxplot(x=df['engagement_rate_log'])
plt.title("After Transformation")
plt.show()

df['engagement_rate_log'].kurtosis()

fig, axes = plt.subplots(1, 3, figsize=(15,5))

sns.boxplot(x=df['engagement_rate'], ax=axes[0])
axes[0].set_title("Original")

sns.boxplot(x=df['engagement_rate_capped'], ax=axes[1])
axes[1].set_title("Capped")

sns.boxplot(x=df['engagement_rate_log'], ax=axes[2])
axes[2].set_title("Capped + Log Transformed")

plt.show()

"""# **Outcomes **
• Dataset reduced to clean, consistent, and analysis-ready form.
• All engagement metrics standardized.
• Categories harmonized for accurate ‘groupby’ summaries.
• Outliers flagged to avoid distortion in statistical analysis.

# **Data Exploration using Visualization**

## **Scatterplot for Likes vs Impressions**
"""

#Scatterplot for Likes vs Impressions
plt.figure(figsize=(8,6))
sns.scatterplot(x='impression_count', y='likes', data=df, alpha=0.6)
plt.title("Scatter Plot: Likes vs Impressions")
plt.xlabel("Impression Count")
plt.ylabel("Likes")
plt.show()

#Adding Trend Line

sns.lmplot(x='impression_count', y='likes', data=df, scatter_kws={'alpha':0.5}, line_kws={'color':'red'})
plt.title("Likes vs Impressions with Trend Line")
plt.show()

"""Clear positive correlation; posts with higher
impressions tend to get more likes. Outliers highlight viral posts.

## **Line: daily engagement trend**
"""

#Line: daily engagement trend
# Ensure posted_at is datetime
df['posted_at'] = pd.to_datetime(df['posted_at'], errors='coerce')

# Create engagement_score if not already
df['engagement_score'] = df['likes'] + df['comments'] + df['shares']

# Group by date
daily_engagement = df.groupby(df['posted_at'].dt.date)['engagement_score'].sum().reset_index()

plt.figure(figsize=(10,6))
sns.lineplot(x='posted_at', y='engagement_score', data=daily_engagement, marker='o')
plt.title("Daily Engagement Trend")
plt.xlabel("Date")
plt.ylabel("Total Engagement Score")
plt.xticks(rotation=45)
plt.show()

"""Engagement peaks in evenings (6–9 PM),
confirming best posting times.
"""

#Barplot: posts by category

post_counts = df['post_type'].value_counts()
print(post_counts)

# Plotting

plt.figure(figsize=(10,6))
sns.barplot(x=post_counts.index, y=post_counts.values, palette="viridis")
# Add text labels on bars
for i, v in enumerate(post_counts.values):
    plt.text(i, v, str(v), ha='center', va='bottom')
plt.title("Posts by Category")

plt.xlabel("Post Category")
plt.ylabel("Number of Posts")
plt.xticks(rotation=45)
plt.show()

"""Lifestyle/Travel dominates engagement; Tech
posts drive discussions.

## **Piechart: Gender distribution**
"""

#Piechart: gender distribution
fig=plt.figure(figsize=(10,10))
gender_counts = df['gender'].value_counts()
plt.pie(gender_counts, labels=gender_counts.index, autopct='%1.1f%%', startangle=90)
plt.title("Gender Distribution")
plt.show()

"""Balanced audience, with slightly higher male
participation.

## **Histogram: Age Distribution**
"""

#Histogram: age
plt.figure(figsize=(10,6))
sns.histplot(df['age'], bins=20, kde=True)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

""": Younger users (18–24) are most active; engagement drops
after 35.

## **Boxplot for 'engagement rate'**
"""

#Boxplot: engagement rate
plt.figure(figsize=(10,6))
sns.boxplot(x='post_type', y='engagement_rate_log', data=df)
plt.title("Engagement Rate by Post Type")
plt.xlabel("Post Type")
plt.ylabel("Engagement Rate")
plt.show()

"""After Outlier Trearment, Median engagement stable around 4–5%; outliers
show viral spikes.

## **Count plot Analysis for 'post type'**
"""

#Count plot:  post type
plt.figure(figsize=(10,6))
sns.countplot(x='post_type', data=df, palette="viridis")
plt.title("Count of Posts by Type")
plt.xlabel("Post Type")
plt.ylabel("Count")
plt.show()

"""Photos are most frequent; videos less frequent but
higher watch time.

## **Bar plot: Average likes by category**
"""

#Bar plot: avg likes by category
avg_likes_by_category = df.groupby('post_type')['likes'].mean()
plt.figure(figsize=(10,6))
sns.barplot(x=avg_likes_by_category.index, y=avg_likes_by_category.values, palette="viridis")
for i, v in enumerate(avg_likes_by_category.values):
    plt.text(i, v, str(v), ha='center', va='bottom')

plt.title("Average Likes by Post Type")
plt.xlabel("Post Type")
plt.ylabel("Average Likes")
plt.show()

"""Lifestyle/Travel leads;
Food/Entertainment shows viral potential.

## **Violin: followers vs sentiment**
"""

# Violin: followers vs sentiment
plt.figure(figsize=(10,6))
sns.violinplot(x='sentiment', y='follower_count', data=df, palette="viridis")
plt.title("Followers vs Sentiment")
plt.xlabel("Sentiment")
plt.ylabel("Followers")
plt.show()

"""Positive sentiment posts attract higher
engagement across follower ranges.

## **Pair plot: numeric features**
"""

#Pair plot: numeric features
sns.pairplot(df[num_cols])
plt.show()

"""Likes, shares, and impressions cluster
together; watch_time behaves differently.

## **Heatmap: correlation matrix**
"""

#Heatmap: correlation matrix
plt.figure(figsize=(10,6))
sns.heatmap(df[num_cols].corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

"""Strong correlation between impressionns and
likes; weak correlation between followers and engagement rate.

## **Swarm plot: engagement vs device**
"""

#Swarm plot: engagement vs device

plt.figure(figsize=(10,6))
sns.swarmplot(x='device_type', y='engagement_score', data=df, palette="Set2", size=5)
plt.title("Swarm Plot: Engagement vs Device Type")
plt.xlabel("Device Type")
plt.ylabel("Engagement Score")
plt.xticks(rotation=45)
plt.show()

"""Mobile dominates engagement
volume; desktop shows deeper watch time.

# **1. Interactive Line Chart (Daily Engagement Trend)**
"""

import plotly.express as px

daily_engagement = df.groupby(df['posted_at'].dt.date)['engagement_score'].sum().reset_index()

fig = px.line(daily_engagement, x='posted_at', y='engagement_score',
              title="Interactive Daily Engagement Trend",
              markers=True)
fig.show()

"""Allows zooming into daily/weekly engagement spikes.

# **2. Interactive Bar Chart (Posts by Category)**
"""

category_counts = df['post_category'].value_counts().reset_index()
category_counts.columns = ['post_category','count']

fig = px.bar(category_counts, x='post_category', y='count',
             text='count', title="Interactive Posts by Category",
             color='count', color_continuous_scale='Viridis')
fig.update_traces(texttemplate='%{text}', textposition='outside')
fig.show()

"""Interactive hover reveals exact post counts per category.

# **3. Interactive Bubble Chart (Engagement vs Followers)**
: Bubble sizes show engagement score; hover reveals metadata
(user, country).
"""

fig = px.scatter(df, x='follower_count', y='engagement_rate',
                 size='likes', color='sentiment',
                 hover_data=['post_category','device_type'],
                 title="Interactive Bubble Chart: Engagement vs Followers")
fig.show()

"""# **General Key insights: **
• Content: Photos and videos are the strongest formats.

• Audience: Younger users and mobile devices drive majority engagement.

• Timing: Evenings are optimal for impressions.

• Sentiment: Positive posts outperform; negative posts spark discussions.

• Geography: India and USA lead in engagement; Brazil/Indonesia show growth
potential.
"""